name: Daily Job Alert

on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node job-alert.js
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
